Task7
rayblair06/learning-nodejs pull request #14
Opened 2022-02-08 16:19 UTC by rayblair06

WIP

2022-02-13 21:27 UTC, Dmitry-White requested changes

2022-02-13 21:27 UTC, Dmitry-White commented on tests/feature/controllers/group.test.js
> +const supertest = require('supertest');
Consider using the same module system for all imports in your project.

2022-02-13 21:27 UTC, Dmitry-White commented on tests/feature/controllers/user.test.js
> +const { app } = require('../../../src/app');
Same as above.

2022-02-13 21:27 UTC, Dmitry-White commented on tests/feature/controllers/group.test.js
> +                {
I can see that these objects are the same across several tests.
Consider always preparing test dummies before at the beginning of the file and reusing them.

2022-02-13 21:27 UTC, Dmitry-White commented on tests/feature/controllers/base.test.js
> +        expect(response.statusCode).toBe(200);
Consider using the "http-status-code" library that you've added to the business logic already, that was the main purpose actually :)

2022-02-13 21:27 UTC, Dmitry-White commented on tests/feature/controllers/user.test.js
> +        jest.spyOn(User, 'findAll').mockImplementation(() => {
Consider extracting all the `jest.spyOn`s mocking logic into a utils file a the `tests/` level.
You can write some wrapper function around `jest.spyOn` that will expect a method call and a returned value as arguments. That way each call to that wrapper function will have its on stuff mocked in closure.

2022-02-13 21:27 UTC, Dmitry-White commented on tests/feature/controllers/user.test.js
> +        jest.spyOn(User, 'findAll').mockImplementation(() => {
And drastically reduce repetition of mocking logic :)

2022-02-13 21:27 UTC, Dmitry-White commented on tests/unit/services/group.test.js
> +        const output = await GroupService.findById('79836ba5-e47f-4322-a498-53e7744189ad');
Consider using constants and functions to reduce repeated values and object and reuse as much as possible.

2022-02-13 21:27 UTC, Dmitry-White commented on tests/unit/services/user.test.js
> +    test('It can suggest usernames', async () => {
Also, try using `test.each` and `describe.each` for tests with repeated structure

2022-02-15 10:31 UTC, rayblair06 commented
Thanks for taking the time to review my PR @Dmitry-White

I have made the following changes based on your advice.
- Replaced all `require` with `import`.
- `supertest` is now within its own `request` mock module.
- Wrapper module for `jest.spyOn`.
- Model 'Fakes' will mock the called function, if data is passed it will use that else it will use 'Dummie' data.
- TestSuite is now initialised with model Fake.
- Used `test.each` to provide more testcases for 'It can suggest username' test.
- General refactoring and clean up.

2022-02-15 10:45 UTC, Dmitry-White approved these changes
Looks awesome!

2022-02-15 10:47 UTC, merged